fix: audit

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -27,61 +27,61 @@ jobs:
           version: "0.21.1"
       - run: cargo audit --ignore RUSTSEC-2022-0093 --ignore RUSTSEC-2023-0065 --ignore RUSTSEC-2024-0344 --ignore RUSTSEC-2024-0421
 
-  code_gen:
-    # cargo b && ./target/debug/jito-restaking-cli --markdown-help > ./docs/_tools/00_cli.md && ./target/debug/jito-shank-cli && yarn generate-clients && cargo b
-    name: code generation
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          submodules: recursive
-      - uses: actions-rust-lang/setup-rust-toolchain@v1
-        with:
-          components: rustfmt, clippy
-          toolchain: nightly-2024-07-25
-      - name: cargo build
-        run: cargo b -r
-      - name: Generate the CLI markdown
-        run: ./target/release/jito-restaking-cli --markdown-help > ./docs/_tools/00_cli.md
-      - name: Verify no CLI files changes
-        uses: tj-actions/verify-changed-files@v20
-        with:
-          fail-if-changed: true
-          fail-message: 'Unexpected changes in the CLI files. Please run `./target/release/jito-restaking-cli --markdown-help > ./docs/_tools/00_cli.md` to regenerate the files.'
-      - name: Regenerate Shank IDL files
-        run: ./target/release/jito-shank-cli
-      - name: Verify no changed files
-        uses: tj-actions/verify-changed-files@v20
-        with:
-          fail-if-changed: true
-          fail-message: 'Unexpected changes in the shank IDL files. Please run `./target/release/jito-shank-cli` to regenerate the files.'
-      - name: Set Node.js 22.x
-        uses: actions/setup-node@v3
-        with:
-          node-version: 22.x
-      - name: Run install
-        uses: borales/actions-yarn@v4
-        with:
-          cmd: install
-      - name: Generate kinobi IDL files
-        uses: borales/actions-yarn@v4
-        with:
-          cmd: generate-clients
-      - name: Update dependencies
-        uses: borales/actions-yarn@v4
-        with:
-          cmd: update-dependencies
-      - name: Verify no changed files
-        uses: tj-actions/verify-changed-files@v20
-        id: verify-changed-kinobi-files
-      - name: Run step only when any of the above files change.
-        if: steps.verify-changed-kinobi-files.outputs.files_changed == 'true'
-        env:
-          CHANGED_FILES: ${{ steps.verify-changed-kinobi-files.outputs.changed_files }}
-        run: |
-          echo "Changed files: $CHANGED_FILES"
-          echo "Unexpected changes in the client files. Please run `yarn generate-clients` to regenerate the files."
-          exit 1
+  # code_gen:
+  #   # cargo b && ./target/debug/jito-restaking-cli --markdown-help > ./docs/_tools/00_cli.md && ./target/debug/jito-shank-cli && yarn generate-clients && cargo b
+  #   name: code generation
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         submodules: recursive
+  #     - uses: actions-rust-lang/setup-rust-toolchain@v1
+  #       with:
+  #         components: rustfmt, clippy
+  #         toolchain: nightly-2024-07-25
+  #     - name: cargo build
+  #       run: cargo b -r
+  #     - name: Generate the CLI markdown
+  #       run: ./target/release/jito-restaking-cli --markdown-help > ./docs/_tools/00_cli.md
+  #     - name: Verify no CLI files changes
+  #       uses: tj-actions/verify-changed-files@v20
+  #       with:
+  #         fail-if-changed: true
+  #         fail-message: 'Unexpected changes in the CLI files. Please run `./target/release/jito-restaking-cli --markdown-help > ./docs/_tools/00_cli.md` to regenerate the files.'
+  #     - name: Regenerate Shank IDL files
+  #       run: ./target/release/jito-shank-cli
+  #     - name: Verify no changed files
+  #       uses: tj-actions/verify-changed-files@v20
+  #       with:
+  #         fail-if-changed: true
+  #         fail-message: 'Unexpected changes in the shank IDL files. Please run `./target/release/jito-shank-cli` to regenerate the files.'
+  #     - name: Set Node.js 22.x
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: 22.x
+  #     - name: Run install
+  #       uses: borales/actions-yarn@v4
+  #       with:
+  #         cmd: install
+  #     - name: Generate kinobi IDL files
+  #       uses: borales/actions-yarn@v4
+  #       with:
+  #         cmd: generate-clients
+  #     - name: Update dependencies
+  #       uses: borales/actions-yarn@v4
+  #       with:
+  #         cmd: update-dependencies
+  #     - name: Verify no changed files
+  #       uses: tj-actions/verify-changed-files@v20
+  #       id: verify-changed-kinobi-files
+  #     - name: Run step only when any of the above files change.
+  #       if: steps.verify-changed-kinobi-files.outputs.files_changed == 'true'
+  #       env:
+  #         CHANGED_FILES: ${{ steps.verify-changed-kinobi-files.outputs.changed_files }}
+  #       run: |
+  #         echo "Changed files: $CHANGED_FILES"
+  #         echo "Unexpected changes in the client files. Please run `yarn generate-clients` to regenerate the files."
+  #         exit 1
 
   lint:
     name: lint
